"""Minimal one-time setup helpers for the AgentCore Payments example.

Portions are adapted from the AWS AgentCore Payments tutorial utilities
identified in NOTICE and remain subject to LICENSE-APACHE.
"""

from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path
from typing import Any

import boto3
from botocore.exceptions import ClientError

HERE = Path(__file__).resolve().parent
DEFAULT_ENV_PATH = HERE / ".env"

CONTROL_PLANE_ROLE = "LangChainAgentCorePaymentsControlPlaneRole"
MANAGEMENT_ROLE = "LangChainAgentCorePaymentsManagementRole"
PROCESS_PAYMENT_ROLE = "LangChainAgentCorePaymentsProcessPaymentRole"
RESOURCE_RETRIEVAL_ROLE = "LangChainAgentCorePaymentsResourceRetrievalRole"

PAYMENT_ROLE_DEFINITIONS = {
    CONTROL_PLANE_ROLE: {
        "description": "LangChain AgentCore Payments control plane",
        "trust": "account",
        "allow": [
            "bedrock-agentcore:CreatePaymentManager",
            "bedrock-agentcore:GetPaymentManager",
            "bedrock-agentcore:ListPaymentManagers",
            "bedrock-agentcore:DeletePaymentManager",
            "bedrock-agentcore:UpdatePaymentManager",
            "bedrock-agentcore:CreatePaymentConnector",
            "bedrock-agentcore:GetPaymentConnector",
            "bedrock-agentcore:ListPaymentConnectors",
            "bedrock-agentcore:DeletePaymentConnector",
            "bedrock-agentcore:UpdatePaymentConnector",
            "bedrock-agentcore:CreatePaymentCredentialProvider",
            "bedrock-agentcore:GetPaymentCredentialProvider",
            "bedrock-agentcore:ListPaymentCredentialProviders",
            "bedrock-agentcore:DeletePaymentCredentialProvider",
            "bedrock-agentcore:UpdatePaymentCredentialProvider",
            "bedrock-agentcore:CreateTokenVault",
        ],
        "pass_role": True,
        "secrets_manager_write": True,
    },
    MANAGEMENT_ROLE: {
        "description": "LangChain AgentCore Payments session and instrument management",
        "trust": "account",
        "allow": [
            "bedrock-agentcore:CreatePaymentInstrument",
            "bedrock-agentcore:GetPaymentInstrument",
            "bedrock-agentcore:ListPaymentInstruments",
            "bedrock-agentcore:DeletePaymentInstrument",
            "bedrock-agentcore:GetPaymentInstrumentBalance",
            "bedrock-agentcore:CreatePaymentSession",
            "bedrock-agentcore:GetPaymentSession",
            "bedrock-agentcore:ListPaymentSessions",
            "bedrock-agentcore:DeletePaymentSession",
            "bedrock-agentcore:UpdatePaymentSession",
        ],
        "deny": ["bedrock-agentcore:ProcessPayment"],
    },
    PROCESS_PAYMENT_ROLE: {
        "description": "LangChain AgentCore Payments runtime processing",
        "trust": "account",
        "allow": [
            "bedrock-agentcore:ProcessPayment",
            "bedrock-agentcore:GetPaymentInstrument",
            "bedrock-agentcore:GetPaymentInstrumentBalance",
            "bedrock-agentcore:GetPaymentSession",
        ],
    },
    RESOURCE_RETRIEVAL_ROLE: {
        "description": "LangChain AgentCore Payments credential retrieval",
        "trust": "service",
        "allow": [
            "bedrock-agentcore:GetWorkloadAccessToken",
            "bedrock-agentcore:CreateWorkloadIdentity",
            "bedrock-agentcore:GetResourcePaymentToken",
        ],
        "secrets_manager_read": True,
    },
}


def require_env(name: str) -> str:
    """Return a required environment value without printing it."""
    value = os.environ.get(name, "").strip()
    if not value or value.startswith("<"):
        raise ValueError(f"Missing {name}. Add it to the local .env file.")
    return value


def write_env(
    updates: dict[str, str],
    env_path: Path = DEFAULT_ENV_PATH,
) -> None:
    """Idempotently update an env file without logging any values."""
    existing_lines = (
        env_path.read_text(encoding="utf-8").splitlines(keepends=True)
        if env_path.exists()
        else []
    )
    remaining = {key: str(value) for key, value in updates.items()}
    output: list[str] = []

    for line in existing_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            output.append(line)
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in remaining:
            output.append(f"{key}={remaining.pop(key)}\n")
        else:
            output.append(line)

    if remaining:
        if output and output[-1].strip():
            output.append("\n")
        output.append("# Generated by setup_agentcore_payments.ipynb\n")
        output.extend(
            f"{key}={value}\n" for key, value in remaining.items()
        )

    env_path.write_text("".join(output), encoding="utf-8")
    try:
        env_path.chmod(0o600)
    except OSError:
        pass
    print("Updated local .env keys:", ", ".join(sorted(updates)))


def client_token() -> str:
    """Return an AgentCore-compatible idempotency token."""
    return f"{uuid.uuid4()}-{uuid.uuid4().hex[:8]}"


def assume_role(
    session: boto3.Session,
    role_arn: str,
    session_name: str,
) -> boto3.Session:
    """Assume a setup role without printing temporary credentials."""
    credentials = session.client("sts").assume_role(
        RoleArn=role_arn,
        RoleSessionName=session_name,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=credentials["AccessKeyId"],
        aws_secret_access_key=credentials["SecretAccessKey"],
        aws_session_token=credentials["SessionToken"],
        region_name=session.region_name,
    )


def wait_for_status(
    get_resource,
    expected_status: str,
    *,
    timeout_seconds: int = 120,
    poll_seconds: int = 5,
    **kwargs: Any,
) -> dict[str, Any]:
    """Poll an AgentCore resource until it reaches the expected status."""
    deadline = time.time() + timeout_seconds
    while True:
        response = get_resource(**kwargs)
        status = response.get("status") or response.get(
            "paymentInstrument",
            {},
        ).get("status")
        print("Current status:", status)
        if isinstance(status, str) and status.endswith("_FAILED"):
            raise RuntimeError(f"Resource entered terminal state {status}.")
        if status == expected_status:
            return response
        if time.time() >= deadline:
            raise TimeoutError(
                f"Resource did not reach {expected_status} within "
                f"{timeout_seconds} seconds."
            )
        time.sleep(poll_seconds)


def is_not_found(error: ClientError) -> bool:
    """Return whether an AWS API error means the resource is already gone."""
    code = error.response.get("Error", {}).get("Code", "")
    return code in {"ResourceNotFoundException", "NotFoundException"}


def wait_for_deleted(
    get_resource,
    label: str,
    *,
    timeout_seconds: int = 120,
    poll_seconds: int = 5,
    **kwargs: Any,
) -> None:
    """Poll until an AgentCore resource is deleted."""
    deadline = time.time() + timeout_seconds
    while True:
        try:
            response = get_resource(**kwargs)
        except ClientError as error:
            if is_not_found(error):
                print(f"{label}: deleted")
                return
            raise

        status = response.get("status") or response.get(
            "paymentInstrument",
            {},
        ).get("status")
        if status == "DELETED":
            print(f"{label}: deleted")
            return
        if isinstance(status, str) and status.endswith("_FAILED"):
            raise RuntimeError(
                f"{label} entered terminal state {status}."
            )
        if time.time() >= deadline:
            raise TimeoutError(
                f"{label} was not deleted within {timeout_seconds} seconds."
            )
        time.sleep(poll_seconds)


def delete_payment_roles(region: str) -> None:
    """Delete only the four example roles and their known inline policies."""
    iam = boto3.Session(region_name=region).client("iam")
    known_policies = {
        "AgentCorePaymentsAllow",
        "AgentCorePaymentsDeny",
        "AgentCorePaymentsPassRole",
    }

    for role_name in PAYMENT_ROLE_DEFINITIONS:
        try:
            paginator = iam.get_paginator("list_role_policies")
            policy_names = {
                policy_name
                for page in paginator.paginate(RoleName=role_name)
                for policy_name in page.get("PolicyNames", [])
            }
            unexpected = policy_names - known_policies
            if unexpected:
                raise RuntimeError(
                    f"Refusing to delete {role_name}: it has unexpected "
                    f"inline policies {sorted(unexpected)}. Review it in IAM."
                )
            for policy_name in sorted(policy_names):
                iam.delete_role_policy(
                    RoleName=role_name,
                    PolicyName=policy_name,
                )
            iam.delete_role(RoleName=role_name)
            print(f"IAM role deleted: {role_name}")
        except iam.exceptions.NoSuchEntityException:
            print(f"IAM role already absent: {role_name}")
        except ClientError as error:
            code = error.response.get("Error", {}).get("Code", "")
            if code == "NoSuchEntity":
                print(f"IAM role already absent: {role_name}")
                continue
            if code == "DeleteConflict":
                raise RuntimeError(
                    f"Could not delete {role_name}. Remove any attached "
                    "managed policies or instance-profile links in IAM, then "
                    "rerun cleanup."
                ) from error
            raise


def setup_payment_roles(region: str) -> dict[str, str]:
    """Create or update the four least-privilege tutorial roles."""
    session = boto3.Session(region_name=region)
    sts = session.client("sts")
    iam = session.client("iam")

    identity = sts.get_caller_identity()
    account_id = identity["Account"]
    caller_arn = identity["Arn"]

    principals = [f"arn:aws:iam::{account_id}:root"]
    if ":assumed-role/" in caller_arn:
        role_name = caller_arn.split(":")[-1].split("/")[1]
        try:
            principals.append(iam.get_role(RoleName=role_name)["Role"]["Arn"])
        except Exception:
            principals.append(
                f"arn:aws:iam::{account_id}:role/{role_name}"
            )

    account_trust = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {"AWS": principals},
                "Action": "sts:AssumeRole",
            }
        ],
    }
    service_trust = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "bedrock-agentcore.amazonaws.com"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                    "StringEquals": {"aws:SourceAccount": account_id}
                },
            }
        ],
    }

    role_arns: dict[str, str] = {}
    created = 0
    aliases = {
        CONTROL_PLANE_ROLE: "control_plane",
        MANAGEMENT_ROLE: "management",
        PROCESS_PAYMENT_ROLE: "process_payment",
        RESOURCE_RETRIEVAL_ROLE: "resource_retrieval",
    }

    for role_name, definition in PAYMENT_ROLE_DEFINITIONS.items():
        trust = (
            service_trust
            if definition["trust"] == "service"
            else account_trust
        )
        try:
            role = iam.get_role(RoleName=role_name)["Role"]
            iam.update_assume_role_policy(
                RoleName=role_name,
                PolicyDocument=json.dumps(trust),
            )
        except iam.exceptions.NoSuchEntityException:
            role = iam.create_role(
                RoleName=role_name,
                AssumeRolePolicyDocument=json.dumps(trust),
                Description=definition["description"],
            )["Role"]
            created += 1

        role_arns[aliases[role_name]] = role["Arn"]
        statements: list[dict[str, Any]] = [
            {
                "Sid": "AgentCorePayments",
                "Effect": "Allow",
                "Action": definition["allow"],
                "Resource": (
                    f"arn:aws:bedrock-agentcore:{region}:{account_id}:*"
                ),
            }
        ]

        if definition.get("secrets_manager_write"):
            statements.append(
                {
                    "Sid": "SecretsManagerWrite",
                    "Effect": "Allow",
                    "Action": [
                        "secretsmanager:CreateSecret",
                        "secretsmanager:PutSecretValue",
                        "secretsmanager:UpdateSecret",
                        "secretsmanager:DeleteSecret",
                        "secretsmanager:TagResource",
                    ],
                    "Resource": "*",
                }
            )

        if definition.get("secrets_manager_read"):
            statements.extend(
                [
                    {
                        "Sid": "SecretsManagerRead",
                        "Effect": "Allow",
                        "Action": "secretsmanager:GetSecretValue",
                        "Resource": (
                            "arn:aws:secretsmanager:*:"
                            f"{account_id}:secret:"
                            "bedrock-agentcore-identity*"
                        ),
                    },
                    {
                        "Sid": "StsSetContext",
                        "Effect": "Allow",
                        "Action": "sts:SetContext",
                        "Resource": f"arn:aws:sts::{account_id}:self",
                    },
                ]
            )

        iam.put_role_policy(
            RoleName=role_name,
            PolicyName="AgentCorePaymentsAllow",
            PolicyDocument=json.dumps(
                {
                    "Version": "2012-10-17",
                    "Statement": statements,
                }
            ),
        )

        if definition.get("deny"):
            iam.put_role_policy(
                RoleName=role_name,
                PolicyName="AgentCorePaymentsDeny",
                PolicyDocument=json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Deny",
                                "Action": definition["deny"],
                                "Resource": (
                                    "arn:aws:bedrock-agentcore:"
                                    f"{region}:{account_id}:*"
                                ),
                            }
                        ],
                    }
                ),
            )

        if definition.get("pass_role"):
            resource_role_arn = (
                f"arn:aws:iam::{account_id}:role/"
                f"{RESOURCE_RETRIEVAL_ROLE}"
            )
            iam.put_role_policy(
                RoleName=role_name,
                PolicyName="AgentCorePaymentsPassRole",
                PolicyDocument=json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Action": "iam:PassRole",
                                "Resource": resource_role_arn,
                                "Condition": {
                                    "StringEquals": {
                                        "iam:PassedToService": (
                                            "bedrock-agentcore.amazonaws.com"
                                        )
                                    }
                                },
                            }
                        ],
                    }
                ),
            )

    if created:
        print(
            f"Created {created} IAM role(s); waiting for propagation."
        )
        time.sleep(10)

    print("AgentCore Payments IAM roles are ready.")
    return role_arns
